### PR TITLE
transpile all valid selected files in tree view

### LINKED ISSUE #2: Transpile all selected files in tree view
When multiple files are selected in treeview, transpile should transpile all of the selected files

### PR DESCRIPTION
**Pull request by UziTech**
This will run all selected files in tree-view of a given file type through the transpiler.

I used a [`shouldDisplay`](https://atom.io/docs/api/v1.17.2/ContextMenuManager#instance-add) method on the context menu so it will show up in the context menu if they right click on an invalid file type but a valid file type is selected.

It will only send the valid file types to the transpiler.

fixes #2

### CODE REVIEW

**Comment by UziTech** [comment]
@danielbayley any feedback on this?

**Comment by danielbayley** [comment]
@UziTech Sorry, thanks for the PR… and the reminder! I'll take a look shortly.

**Comment by UziTech** [comment]
Any update?

**Comment by UziTech** [comment]
🙃

**Comment by UziTech** [comment]
@danielbayley is this going to be fixed any time soon?

**Comment by UziTech** [comment]
@danielbayley this would still be nice to have this fixed

**Comment by UziTech** [comment]
@danielbayley is this repo maintained?

**Comment by UziTech** [comment]
@danielbayley still an issue

**Pull request closed without merging**
